---
version: "3.8"

secrets:
  config_json:
    file: secrets.json

services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: vtt
    volumes:
      - type: bind
        source: ~/foundryvtt_data
        target: /data
    environment:
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
    secrets:
      - source: config_json
        target: config.json